apiVersion: v1
kind: Pod
metadata:
  name: alpine2
spec:
  containers:
  - image: byrnedo/alpine-curl
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always
